config/routes.rb
Rails.application.routes.draw do

  root 'static#home'

  get '/about', to:'static#about', as: :about

  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update_attributes(post_params)
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

private

  def post_params
    params.require(:post).permit(:title, :author, :body)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home

  end

  def about
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>
<%= link_to 'Posts', posts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>
<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<div class = "blog_form">
  <%= form_for @post do |f| %>
    <%= f.label :title %>:
    <%= f.text_field :title %>

    <%= f.label :author %>
    <%= f.text_field :author %>

    <%= f.label :body %>
    <%= f.text_field :body %>

    <%= f.submit %>
  <% end %>
</div>

app/views/posts/index.html.erb
<h1>Posts</h1>

<p><%= link_to 'New Post', new_post_path %></p>

<% @posts.each do |post| %>

<h2><%= post.title %></h2>
<h3><%= post.author %></h3>
<p><%= post.body %></p>
<%= link_to 'Show Post', post_path(post.id) %>
<%= link_to 'Edit Post', edit_post_path(post.id) %>
<%= link_to 'Delete Post', post, method: :delete %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<div class = "blog_form">
  <%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>

  <% end %>
</div>

app/views/posts/show.html.erb
<h1>Post</h1>
<h2><%= @post.title %></h2>
<h3><%= @post.author %></h3>
<p><%= @post.body %></p>

<%= link_to 'Back', posts_path %>